# Makefile para criar um arquivo zip para o Chrome

# Nome do arquivo de saída
OUTPUT_FILE = gruppy.zip

# Diretório de origem
SOURCE_DIR = .

all:
	zip -r $(OUTPUT_FILE) $(SOURCE_DIR)/*

clean:
	rm -f $(OUTPUT_FILE)