# Makefile para criar um arquivo xpi para o Firefox

# Nome do arquivo de saída
OUTPUT_FILE = gruppy.xpi

# Diretório de origem
SOURCE_DIR = .

all:
	zip -r $(OUTPUT_FILE) $(SOURCE_DIR)/*

clean:
	rm -f $(OUTPUT_FILE)